version: "3.9"

services:
  albedo:
    container_name: Albedo
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      - PYTHON_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/albedo
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your_secret_key_here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - postgres
      - redis
    restart: always
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "4000", "--reload"]

  postgres:
    container_name: AlbedoPostgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=albedo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: AlbedoRedis
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
  redis_data: